### ISSUE TITLE
Add GitHub usernames to team page

### ISSUE THREAD

**Issue by embray** [astropy/astropy.github.com#323] opened 2019-05-15 08:30 UTC
The team page lists names of subpackage maintainers but not GitHub usernames, which are not always obvious.

(One thing I miss from the Trac issue tracker is you could add sub-component "owners" who would be assigned to tickets relevant to their interest areas.)

In practice with Astropy a maintainer typically does this sort of triage manually but it would help for new contributors to get the right eyes on their work right away.

**Comment by eteq** [comment] 2019-06-05 20:33
Good point - the catch is that I think it might make the page start looking really busy if all names also had usernames.  Perhaps we should make the names instead be links to the github user page?

The easiest thing would probably be to insert a mapping of names to github into the javascript that generates the table and have it automatically replace the text with the relevant hyperlink...

**Comment by pllim** [comment] 2020-09-08 18:23
@embray , regard on your note about "links to github profiles and/or personal websites/social media" -- I am wary of the latter (personal website/social media) as some people might value privacy more than others, so if you want to do that, please make it opt-in only and optional.

**Comment by embray** [comment] 2020-09-09 20:26
Definitely anything anyone wants to put on the team page, even including GH profiles, should be opt-in.  I think we need to create a database of some sort (as in a plain text file, such as a YAML file) where project contributors can add whatever they wish via a PR.  This is how the Software Carpentry project manages its [instructors page](https://carpentries.org/instructors/)

**Comment by pllim** [comment] 2020-09-09 20:34
@embray , how is that different from what we already do (except the new concept of gallery)? We already have https://github.com/astropy/astropy.github.com/blob/master/roles.json and there are outstanding PRs to update it.

**Comment by embray** [comment] 2020-09-09 20:40
Oh I didn't realize that was the case.  I think what I had in mind was inverting it: By instead having a database of people, and for each person list any roles they adopt.  There could still be a separate file like the above containing additional metadata about each role.

**Comment by pllim** [comment] 2020-10-19 17:27
This is now a pre-requisite for astropy/astropy-project#160

**Comment by dhomeier** [comment] 2023-05-03 21:09
This could include adding actual links to their profile pages, see #498.

**Comment by pllim** [comment] 2024-02-29 22:52
I think this is duplicate of #183

**Closed by pllim** 2024-02-29 22:52 UTC
Labels: roles and team
